export enum CurrencySign {
    USD = '$',
    EUR = '€',
    GBP = '£',
    AUD = '$',
    CAD = '$',
    CHF = '₣',
    HKD = '$',
    JPY = '¥',
    SGD = '$',
    IDR = '₨',
    KRW = '₩',
    MXN = '$',
    NZD = '$',
    THB = '฿',
    TWD = '$',
    INR = '₹',
    TRY = '£',
    HUF = 'ƒ',
    BRL = '$',
    RUB = '₽',
    SAR = '﷼',
    CNY = '¥'
  }
