"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CurrencyDecimalDigitsEnum;
(function (CurrencyDecimalDigitsEnum) {
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["AUD"] = 2] = "AUD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["CAD"] = 2] = "CAD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["CHF"] = 2] = "CHF";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["EUR"] = 2] = "EUR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["GBP"] = 2] = "GBP";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["HKD"] = 2] = "HKD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["JPY"] = 0] = "JPY";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["SEK"] = 2] = "SEK";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["SGD"] = 2] = "SGD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["USD"] = 2] = "USD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["ZAR"] = 2] = "ZAR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["DKK"] = 2] = "DKK";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["IDR"] = 2] = "IDR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["KRW"] = 0] = "KRW";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["MXN"] = 2] = "MXN";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["MYR"] = 2] = "MYR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["NOK"] = 2] = "NOK";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["NZD"] = 2] = "NZD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["THB"] = 2] = "THB";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["TWD"] = 2] = "TWD";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["INR"] = 2] = "INR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["PLN"] = 2] = "PLN";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["TRY"] = 2] = "TRY";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["CZK"] = 0] = "CZK";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["HUF"] = 2] = "HUF";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["SKK"] = 0] = "SKK";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["CNH"] = 2] = "CNH";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["AED"] = 2] = "AED";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["BRL"] = 2] = "BRL";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["ILS"] = 2] = "ILS";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["RON"] = 2] = "RON";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["RUB"] = 2] = "RUB";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["SAR"] = 2] = "SAR";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["XAU"] = 2] = "XAU";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["XAG"] = 2] = "XAG";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["CNY"] = 2] = "CNY";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["BTC"] = 2] = "BTC";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["BCH"] = 6] = "BCH";
    CurrencyDecimalDigitsEnum[CurrencyDecimalDigitsEnum["Default"] = 2] = "Default";
})(CurrencyDecimalDigitsEnum = exports.CurrencyDecimalDigitsEnum || (exports.CurrencyDecimalDigitsEnum = {}));
//# sourceMappingURL=currency-decimal-digits.enum.js.map